In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('admission_summary.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29886 entries, 0 to 29885
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   admission_id    29886 non-null  int64
 1   patient_name    29886 non-null  object
 2   age             29886 non-null  int64
 3   gender          29886 non-null  object
 4   admission_date  29886 non-null  object
 5   discharge_date  29886 non-null  object
 6   admission_type  29886 non-null  object
 7   diagnosis_name  29886 non-null  object
 8   length_of_stay  29886 non-null  int64
dtypes: int64(3), object(6)
memory usage: 2.1+ MB

In [ ]:
df.shape

(29886, 9)

In [ ]:
df.head()

,admission_id,patient_name,age,gender,admission_date,discharge_date,admission_type,diagnosis_name,length_of_stay
0,1,SHAWn ZAmORA,42,Female,3/4/2022,3/26/2022,Emergency,Arthritis,22
1,2,SHAWn ZAmORA,42,Female,3/4/2022,3/26/2022,Emergency,Arthritis,22
2,3,CYnThIA PAGe,58,Male,4/1/2024,4/19/2024,Emergency,Cancer,18
3,4,dave lOPEZ,33,Female,2/12/2023,2/16/2023,Elective,Hypertension,4
4,5,RoBERT HARris,75,Female,4/15/2020,5/11/2020,Elective,Diabetes,26

In [ ]:
df.isna().sum()

admission_id      0
patient_name      0
age               0
gender            0
admission_date    0
discharge_date    0
admission_type    0
diagnosis_name    0
length_of_stay    0
dtype: int64

In [ ]:
df['patient_name'] = (
    df['patient_name']
    .str.strip()
    .str.title()
)

In [ ]:
df['gender'] = df['gender'].str.strip().str.lower()

In [ ]:
df['gender'] = df['gender'].replace({
    'male': 'Male',
    'female': 'Female'
})

In [ ]:
df['age'] = pd.to_numeric(df['age'], errors='coerce')

In [ ]:
df['admission_date'] = pd.to_datetime(df['admission_date'])
df['discharge_date'] = pd.to_datetime(df['discharge_date'])

In [ ]:
df[['admission_date', 'discharge_date']].isna().sum()

admission_date    0
discharge_date    0
dtype: int64

In [ ]:
df = df.drop_duplicates()

In [ ]:
df = df.drop_duplicates(
    subset=['patient_name', 'admission_date', 'diagnosis_name']
)

In [ ]:
df['calculated_los'] = (
    df['discharge_date'] - df['admission_date']
).dt.days

In [ ]:
df

,admission_id,patient_name,age,gender,admission_date,discharge_date,admission_type,diagnosis_name,length_of_stay,calculated_los
0,1,Shawn Zamora,42,Female,2022-03-04,2022-03-26,Emergency,Arthritis,22,22
2,3,Cynthia Page,58,Male,2024-04-01,2024-04-19,Emergency,Cancer,18,18
3,4,Dave Lopez,33,Female,2023-02-12,2023-02-16,Elective,Hypertension,4,4
4,5,Robert Harris,75,Female,2020-04-15,2020-05-11,Elective,Diabetes,26,26
5,6,Damon Bennett Phd,62,Female,2021-07-02,2021-07-05,Urgent,Arthritis,3,3
...,...,...,...,...,...,...,...,...,...,...
29878,29879,Linda Glenn,34,Female,2021-08-21,2021-09-06,Urgent,Cancer,16,16
29879,29880,Russell Rogers,82,Female,2021-12-18,2021-12-26,Elective,Diabetes,8,8
29880,29881,Carolyn Jenkins,77,Male,2020-03-27,2020-04-18,Urgent,Diabetes,22,22
29883,29884,Elizabeth Morris,15,Female,2020-04-07,2020-05-05,Elective,Cancer,28,28
29885,29886,Carlos Wood,63,Male,2023-04-30,2023-05-25,Urgent,Hypertension,25,25

In [ ]:
df.to_csv('admission_summary_cleaned.csv', index=False)